-- Migration draft for FITMOTOR GABUNG Access sync
-- Generated on 2026-06-08

CREATE TABLE IF NOT EXISTS sync_access_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_name VARCHAR(100) NOT NULL,
    source_file VARCHAR(255) NOT NULL,
    sync_mode ENUM('full','incremental','manual_upload') NOT NULL DEFAULT 'manual_upload',
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    status ENUM('running','success','partial','failed') NOT NULL DEFAULT 'running',
    total_rows INT NOT NULL DEFAULT 0,
    success_rows INT NOT NULL DEFAULT 0,
    failed_rows INT NOT NULL DEFAULT 0,
    notes TEXT NULL
);

CREATE TABLE IF NOT EXISTS sync_access_row_errors (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    dataset_name VARCHAR(100) NOT NULL,
    row_key VARCHAR(255) NULL,
    error_message TEXT NOT NULL,
    raw_payload JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_sync_access_row_errors_run (sync_run_id)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_pembelian (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    no_baris INT NULL,
    status VARCHAR(30) NULL,
    cara_bayar VARCHAR(30) NULL,
    tanggal DATETIME NULL,
    no_order VARCHAR(50) NULL,
    tanggal_order DATETIME NULL,
    no_supplier VARCHAR(50) NULL,
    note TEXT NULL,
    total_qty_order DECIMAL(18,2) NULL,
    total_qty DECIMAL(18,2) NULL,
    total_beli DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    total_retur DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    tanggal_jt DATETIME NULL,
    tanggal_lunas DATETIME NULL,
    jumlah_bayar DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    no_item VARCHAR(50) NULL,
    qty_order DECIMAL(18,2) NULL,
    quantity DECIMAL(18,2) NULL,
    qty_retur DECIMAL(18,2) NULL,
    harga_pokok DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    harga_sp DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    sts_order VARCHAR(30) NULL,
    id_inv VARCHAR(50) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_pembelian_sync (sync_run_id),
    KEY idx_stg_pembelian_trx (no_transaksi),
    KEY idx_stg_pembelian_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_penjualan (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    no_baris INT NULL,
    status VARCHAR(30) NULL,
    cara_bayar VARCHAR(30) NULL,
    tanggal DATETIME NULL,
    no_order VARCHAR(50) NULL,
    tanggal_order DATETIME NULL,
    no_sales VARCHAR(50) NULL,
    no_pelanggan VARCHAR(50) NULL,
    note TEXT NULL,
    total_qty_order DECIMAL(18,2) NULL,
    total_qty DECIMAL(18,2) NULL,
    total_jual DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    total_retur DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    tanggal_jt DATETIME NULL,
    tanggal_lunas DATETIME NULL,
    jumlah_bayar DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    no_item VARCHAR(50) NULL,
    qty_order DECIMAL(18,2) NULL,
    quantity DECIMAL(18,2) NULL,
    qty_retur DECIMAL(18,2) NULL,
    harga_jual DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    harga_sp DECIMAL(18,2) NULL,
    harga_pokok DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    sts_order VARCHAR(30) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_penjualan_sync (sync_run_id),
    KEY idx_stg_penjualan_trx (no_transaksi),
    KEY idx_stg_penjualan_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_service (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_service VARCHAR(50) NOT NULL,
    tanggal DATETIME NULL,
    jam VARCHAR(20) NULL,
    no_pelanggan VARCHAR(50) NULL,
    no_polisi VARCHAR(30) NULL,
    mekanik1 VARCHAR(50) NULL,
    mekanik2 VARCHAR(50) NULL,
    mekanik3 VARCHAR(50) NULL,
    mekanik4 VARCHAR(50) NULL,
    biayam1 DECIMAL(18,2) NULL,
    biayam2 DECIMAL(18,2) NULL,
    biayam3 DECIMAL(18,2) NULL,
    biayam4 DECIMAL(18,2) NULL,
    km_sekarang DECIMAL(18,2) NULL,
    km_berikut DECIMAL(18,2) NULL,
    total_waktu DECIMAL(18,2) NULL,
    status VARCHAR(30) NULL,
    keterangan TEXT NULL,
    subtotal_jasa DECIMAL(18,2) NULL,
    subtotal_item DECIMAL(18,2) NULL,
    subtotal DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    advisor VARCHAR(100) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_service_sync (sync_run_id),
    KEY idx_stg_service_no (no_service),
    KEY idx_stg_service_cabang (kd_cabang),
    KEY idx_stg_service_nopol (no_polisi)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_service_barang (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_service VARCHAR(50) NOT NULL,
    tanggal DATETIME NULL,
    no_pelanggan VARCHAR(50) NULL,
    no_polisi VARCHAR(30) NULL,
    mekanik1 VARCHAR(50) NULL,
    mekanik2 VARCHAR(50) NULL,
    mekanik3 VARCHAR(50) NULL,
    mekanik4 VARCHAR(50) NULL,
    biayam1 DECIMAL(18,2) NULL,
    biayam2 DECIMAL(18,2) NULL,
    biayam3 DECIMAL(18,2) NULL,
    biayam4 DECIMAL(18,2) NULL,
    km_sekarang DECIMAL(18,2) NULL,
    km_berikut DECIMAL(18,2) NULL,
    total_waktu DECIMAL(18,2) NULL,
    status VARCHAR(30) NULL,
    keterangan TEXT NULL,
    subtotal_jasa DECIMAL(18,2) NULL,
    subtotal_item DECIMAL(18,2) NULL,
    subtotal DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    no_baris INT NULL,
    no_item VARCHAR(50) NULL,
    quantity DECIMAL(18,2) NULL,
    qty_retur DECIMAL(18,2) NULL,
    harga DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_service_barang_sync (sync_run_id),
    KEY idx_stg_service_barang_no (no_service),
    KEY idx_stg_service_barang_item (no_item),
    KEY idx_stg_service_barang_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_service_jasa (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_service VARCHAR(50) NOT NULL,
    tanggal DATETIME NULL,
    no_pelanggan VARCHAR(50) NULL,
    no_polisi VARCHAR(30) NULL,
    mekanik1 VARCHAR(50) NULL,
    mekanik2 VARCHAR(50) NULL,
    mekanik3 VARCHAR(50) NULL,
    mekanik4 VARCHAR(50) NULL,
    biayam1 DECIMAL(18,2) NULL,
    biayam2 DECIMAL(18,2) NULL,
    biayam3 DECIMAL(18,2) NULL,
    biayam4 DECIMAL(18,2) NULL,
    km_sekarang DECIMAL(18,2) NULL,
    km_berikut DECIMAL(18,2) NULL,
    total_waktu DECIMAL(18,2) NULL,
    status VARCHAR(30) NULL,
    keterangan TEXT NULL,
    subtotal_jasa DECIMAL(18,2) NULL,
    subtotal_item DECIMAL(18,2) NULL,
    subtotal DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    no_baris INT NULL,
    no_item VARCHAR(50) NULL,
    waktu DECIMAL(18,2) NULL,
    harga DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_service_jasa_sync (sync_run_id),
    KEY idx_stg_service_jasa_no (no_service),
    KEY idx_stg_service_jasa_item (no_item),
    KEY idx_stg_service_jasa_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_service_advisor (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_service VARCHAR(50) NOT NULL,
    advisor VARCHAR(100) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_service_advisor_sync (sync_run_id),
    KEY idx_stg_service_advisor_no (no_service),
    KEY idx_stg_service_advisor_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_item (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_item VARCHAR(50) NOT NULL,
    kode_barcode VARCHAR(100) NULL,
    nama_item VARCHAR(255) NULL,
    jenis VARCHAR(100) NULL,
    satuan VARCHAR(50) NULL,
    harga_pokok DECIMAL(18,2) NULL,
    harga_jual DECIMAL(18,2) NULL,
    harga_jual2 DECIMAL(18,2) NULL,
    harga_jual3 DECIMAL(18,2) NULL,
    quantity DECIMAL(18,2) NULL,
    stok_min DECIMAL(18,2) NULL,
    status_item VARCHAR(50) NULL,
    supplier1 VARCHAR(50) NULL,
    supplier2 VARCHAR(50) NULL,
    supplier3 VARCHAR(50) NULL,
    status_produk VARCHAR(50) NULL,
    rak_barang VARCHAR(100) NULL,
    jasa_waktu DECIMAL(18,2) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_item_sync (sync_run_id),
    KEY idx_stg_item_no (no_item),
    KEY idx_stg_item_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_supplier (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_supplier VARCHAR(50) NOT NULL,
    nama_supplier VARCHAR(255) NULL,
    alamat TEXT NULL,
    kota VARCHAR(100) NULL,
    propinsi VARCHAR(100) NULL,
    kode_post VARCHAR(20) NULL,
    negara VARCHAR(100) NULL,
    telephone VARCHAR(100) NULL,
    fax VARCHAR(100) NULL,
    nama_bank VARCHAR(100) NULL,
    no_account VARCHAR(100) NULL,
    atas_nama VARCHAR(100) NULL,
    kontak_person VARCHAR(100) NULL,
    email VARCHAR(150) NULL,
    note TEXT NULL,
    saldo_awal DECIMAL(18,2) NULL,
    per_tanggal DATETIME NULL,
    jml_bayar DECIMAL(18,2) NULL,
    sisa DECIMAL(18,2) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_supplier_sync (sync_run_id),
    KEY idx_stg_supplier_no (no_supplier),
    KEY idx_stg_supplier_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_mekanik (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_mekanik VARCHAR(50) NOT NULL,
    nama VARCHAR(255) NULL,
    alamat TEXT NULL,
    kota VARCHAR(100) NULL,
    provinsi VARCHAR(100) NULL,
    no_telepon VARCHAR(100) NULL,
    note TEXT NULL,
    keahlian VARCHAR(255) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_mekanik_sync (sync_run_id),
    KEY idx_stg_mekanik_no (no_mekanik),
    KEY idx_stg_mekanik_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_kendaraan_pelanggan (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_polisi VARCHAR(30) NOT NULL,
    nama_pelanggan VARCHAR(255) NULL,
    merek VARCHAR(100) NULL,
    tipe VARCHAR(100) NULL,
    jenis VARCHAR(100) NULL,
    warna VARCHAR(100) NULL,
    tahun_buat VARCHAR(10) NULL,
    telephone VARCHAR(100) NULL,
    grup VARCHAR(100) NULL,
    alamat TEXT NULL,
    note TEXT NULL,
    kategori VARCHAR(100) NULL,
    kota VARCHAR(100) NULL,
    kontak_person VARCHAR(100) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_kendaraan_sync (sync_run_id),
    KEY idx_stg_kendaraan_nopol (no_polisi),
    KEY idx_stg_kendaraan_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_pelanggan (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_pelanggan VARCHAR(50) NOT NULL,
    nama_pelanggan VARCHAR(255) NULL,
    alamat TEXT NULL,
    kota VARCHAR(100) NULL,
    propinsi VARCHAR(100) NULL,
    kode_post VARCHAR(20) NULL,
    negara VARCHAR(100) NULL,
    telephone VARCHAR(100) NULL,
    fax VARCHAR(100) NULL,
    kontak_person VARCHAR(100) NULL,
    note TEXT NULL,
    potongan DECIMAL(18,2) NULL,
    tipe_pot VARCHAR(20) NULL,
    lavel_harga VARCHAR(50) NULL,
    kgrup VARCHAR(50) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_pelanggan_sync (sync_run_id),
    KEY idx_stg_pelanggan_no (no_pelanggan),
    KEY idx_stg_pelanggan_cabang (kd_cabang)
);

CREATE TABLE IF NOT EXISTS stg_access_gabung_member_pelanggan (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    kd_cabang VARCHAR(30) NULL,
    sts_source VARCHAR(50) NULL,
    tanggal_data DATETIME NULL,
    no_pelanggan VARCHAR(50) NOT NULL,
    tipe_member VARCHAR(100) NULL,
    no_polisi VARCHAR(30) NULL,
    raw_payload JSON NULL,
    KEY idx_stg_member_sync (sync_run_id),
    KEY idx_stg_member_pelanggan (no_pelanggan),
    KEY idx_stg_member_nopol (no_polisi)
);

CREATE TABLE IF NOT EXISTS konsolidasi_pembelian_header (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kd_cabang VARCHAR(30) NOT NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    status VARCHAR(30) NULL,
    cara_bayar VARCHAR(30) NULL,
    tanggal DATETIME NULL,
    no_order VARCHAR(50) NULL,
    tanggal_order DATETIME NULL,
    no_supplier VARCHAR(50) NULL,
    note TEXT NULL,
    total_qty_order DECIMAL(18,2) NULL,
    total_qty DECIMAL(18,2) NULL,
    total_beli DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    total_retur DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    tanggal_jt DATETIME NULL,
    tanggal_lunas DATETIME NULL,
    jumlah_bayar DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    source_run_id BIGINT UNSIGNED NULL,
    source_file_date DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kons_pembelian_header (kd_cabang, no_transaksi),
    KEY idx_kons_pembelian_header_supplier (no_supplier)
);

CREATE TABLE IF NOT EXISTS konsolidasi_pembelian_detail (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kd_cabang VARCHAR(30) NOT NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    no_baris INT NOT NULL DEFAULT 0,
    no_item VARCHAR(50) NULL,
    qty_order DECIMAL(18,2) NULL,
    quantity DECIMAL(18,2) NULL,
    qty_retur DECIMAL(18,2) NULL,
    harga_pokok DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    harga_sp DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    sts_order VARCHAR(30) NULL,
    id_inv VARCHAR(50) NULL,
    source_run_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kons_pembelian_detail (kd_cabang, no_transaksi, no_baris, no_item)
);

CREATE TABLE IF NOT EXISTS konsolidasi_penjualan_header (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kd_cabang VARCHAR(30) NOT NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    status VARCHAR(30) NULL,
    cara_bayar VARCHAR(30) NULL,
    tanggal DATETIME NULL,
    no_order VARCHAR(50) NULL,
    tanggal_order DATETIME NULL,
    no_sales VARCHAR(50) NULL,
    no_pelanggan VARCHAR(50) NULL,
    note TEXT NULL,
    total_qty_order DECIMAL(18,2) NULL,
    total_qty DECIMAL(18,2) NULL,
    total_jual DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    total_retur DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    tanggal_jt DATETIME NULL,
    tanggal_lunas DATETIME NULL,
    jumlah_bayar DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    source_run_id BIGINT UNSIGNED NULL,
    source_file_date DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kons_penjualan_header (kd_cabang, no_transaksi),
    KEY idx_kons_penjualan_header_pelanggan (no_pelanggan)
);

CREATE TABLE IF NOT EXISTS konsolidasi_penjualan_detail (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kd_cabang VARCHAR(30) NOT NULL,
    no_transaksi VARCHAR(50) NOT NULL,
    no_baris INT NOT NULL DEFAULT 0,
    no_item VARCHAR(50) NULL,
    qty_order DECIMAL(18,2) NULL,
    quantity DECIMAL(18,2) NULL,
    qty_retur DECIMAL(18,2) NULL,
    harga_jual DECIMAL(18,2) NULL,
    potongan DECIMAL(18,2) NULL,
    harga_sp DECIMAL(18,2) NULL,
    harga_pokok DECIMAL(18,2) NULL,
    total DECIMAL(18,2) NULL,
    sts_order VARCHAR(30) NULL,
    source_run_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kons_penjualan_detail (kd_cabang, no_transaksi, no_baris, no_item)
);

CREATE TABLE IF NOT EXISTS konsolidasi_service (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kd_cabang VARCHAR(30) NOT NULL,
    no_service VARCHAR(50) NOT NULL,
    tanggal DATETIME NULL,
    jam VARCHAR(20) NULL,
    no_pelanggan VARCHAR(50) NULL,
    no_polisi VARCHAR(30) NULL,
    mekanik1 VARCHAR(50) NULL,
    mekanik2 VARCHAR(50) NULL,
    mekanik3 VARCHAR(50) NULL,
    mekanik4 VARCHAR(50) NULL,
    biayam1 DECIMAL(18,2) NULL,
    biayam2 DECIMAL(18,2) NULL,
    biayam3 DECIMAL(18,2) NULL,
    biayam4 DECIMAL(18,2) NULL,
    km_sekarang DECIMAL(18,2) NULL,
    km_berikut DECIMAL(18,2) NULL,
    total_waktu DECIMAL(18,2) NULL,
    status VARCHAR(30) NULL,
    keterangan TEXT NULL,
    subtotal_jasa DECIMAL(18,2) NULL,
    subtotal_item DECIMAL(18,2) NULL,
    subtotal DECIMAL(18,2) NULL,
    diskon DECIMAL(18,2) NULL,
    total_diskon DECIMAL(18,2) NULL,
    pajak DECIMAL(18,2) NULL,
    total_pajak DECIMAL(18,2) NULL,
    total_akhir DECIMAL(18,2) NULL,
    pembayaran DECIMAL(18,2) NULL,
    user_input VARCHAR(100) NULL,
    id_tabel VARCHAR(50) NULL,
    advisor VARCHAR(100) NULL,
    source_run_id BIGINT UNSIGNED NULL,
    source_file_date DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kons_service (kd_cabang, no_service),
    KEY idx_kons_service_pelanggan (no_pelanggan),
    KEY idx_kons_service_nopol (no_polisi)
);
