-- FITMOTOR Access -> MySQL table reconciliation script
-- Generated: 2026-06-25 09:28:40 
-- Review before execution. Access MDB is source of truth.
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `BAGI_HASIL` (
  `STTS` VARCHAR(255) NULL,
  `KATEGORI` VARCHAR(255) NULL,
  `PERSEN_BAGIHASIL` INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_PEMBELIAN_DATA` (
  `NoTransaksi` VARCHAR(255) NULL,
  `Status` VARCHAR(255) NULL,
  `CaraBayar` VARCHAR(255) NULL,
  `Tanggal` DATETIME NULL,
  `NoOrder` VARCHAR(255) NULL,
  `TanggalOrder` DATETIME NULL,
  `NoSupplier` VARCHAR(255) NULL,
  `Note` LONGTEXT NULL,
  `TotalQtyOrder` DOUBLE NULL,
  `TotalQty` DOUBLE NULL,
  `TotalBeli` DOUBLE NULL,
  `Diskon` DOUBLE NULL,
  `TotalDiskon` DOUBLE NULL,
  `Pajak` DOUBLE NULL,
  `TotalPajak` DOUBLE NULL,
  `TotalAkhir` DOUBLE NULL,
  `TotalRetur` DOUBLE NULL,
  `Pembayaran` DOUBLE NULL,
  `TanggalJT` DATETIME NULL,
  `TanggalLunas` DATETIME NULL,
  `JumlahBayar` DOUBLE NULL,
  `User` VARCHAR(255) NULL,
  `IDTabel` VARCHAR(255) NULL,
  `NoBaris` INT NULL,
  `NoItem` VARCHAR(255) NULL,
  `QtyOrder` DOUBLE NULL,
  `Quantity` DOUBLE NULL,
  `QtyRetur` DOUBLE NULL,
  `HargaPokok` DOUBLE NULL,
  `Potongan` DOUBLE NULL,
  `HargaSP` DOUBLE NULL,
  `Total` DOUBLE NULL,
  `StsOrder` TINYINT(1) NULL,
  `IDInv` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_SERVICE_HEADER_DATA` (
  `NoService` VARCHAR(255) NULL,
  `Tanggal` DATETIME NULL,
  `NoPelanggan` VARCHAR(255) NULL,
  `NoPolisi` VARCHAR(255) NULL,
  `Mekanik1` VARCHAR(255) NULL,
  `Mekanik2` VARCHAR(255) NULL,
  `Mekanik3` VARCHAR(255) NULL,
  `Mekanik4` VARCHAR(255) NULL,
  `BiayaM1` DOUBLE NULL,
  `BiayaM2` DOUBLE NULL,
  `BiayaM3` DOUBLE NULL,
  `BiayaM4` DOUBLE NULL,
  `KmSekarang` INT NULL,
  `KmBerikut` INT NULL,
  `TotalWaktu` INT NULL,
  `Status` VARCHAR(255) NULL,
  `Keterangan` LONGTEXT NULL,
  `SubTotalJasa` DOUBLE NULL,
  `SubTotalItem` DOUBLE NULL,
  `SubTotal` DOUBLE NULL,
  `Diskon` DOUBLE NULL,
  `TotalDiskon` DOUBLE NULL,
  `Pajak` DOUBLE NULL,
  `TotalPajak` DOUBLE NULL,
  `TotalAkhir` DOUBLE NULL,
  `Pembayaran` DOUBLE NULL,
  `User` VARCHAR(255) NULL,
  `IDTabel` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_STATISTIK_ITEM_MINGGU_PIVOT` (
  `STS` VARCHAR(255) NULL,
  `NOITEM` VARCHAR(255) NULL,
  `M1` DOUBLE NULL,
  `M2` DOUBLE NULL,
  `M3` DOUBLE NULL,
  `M4` DOUBLE NULL,
  `M5` DOUBLE NULL,
  `M6` DOUBLE NULL,
  `M7` DOUBLE NULL,
  `M8` DOUBLE NULL,
  `M9` INT NULL,
  `M10` INT NULL,
  `M11` INT NULL,
  `M12` INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_TBLITEM_PERBENGKEL_DATA` (
  `NoItem` VARCHAR(255) NULL,
  `KodeBarCode` VARCHAR(255) NULL,
  `NamaItem` VARCHAR(255) NULL,
  `Jenis` VARCHAR(255) NULL,
  `Satuan` VARCHAR(255) NULL,
  `HargaPokok` DOUBLE NULL,
  `HargaJual` DOUBLE NULL,
  `HargaJual2` DOUBLE NULL,
  `HargaJual3` DOUBLE NULL,
  `HJQtyD2` DOUBLE NULL,
  `HJQtyD3` DOUBLE NULL,
  `HJQtyS1` INT NULL,
  `HJQtyS2` DOUBLE NULL,
  `TotalPokok` DOUBLE NULL,
  `Quantity` DOUBLE NULL,
  `StokMin` DOUBLE NULL,
  `StatusItem` VARCHAR(255) NULL,
  `Supplier` VARCHAR(255) NULL,
  `Supplier2` VARCHAR(255) NULL,
  `Supplier3` VARCHAR(255) NULL,
  `StatusProduk` VARCHAR(255) NULL,
  `Gambar` VARCHAR(255) NULL,
  `Note` LONGTEXT NULL,
  `RakBarang` VARCHAR(255) NULL,
  `JasaWaktu` DOUBLE NULL,
  `JasaSatuanWaktu` VARCHAR(255) NULL,
  `JenisKomisi` VARCHAR(255) NULL,
  `KomisiProsen` DOUBLE NULL,
  `KomisiNominal` DOUBLE NULL,
  `Inv_IdAwal` VARCHAR(255) NULL,
  `Inv_JmlAwal` DOUBLE NULL,
  `Inv_HrgAwal` DOUBLE NULL,
  `Inv_TglAwal` DATETIME NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_TBLMEKANIK_DATA` (
  `NOMEKANIK` VARCHAR(255) NULL,
  `NAMA` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_TBLSERVICE_ADVISOR_DATA` (
  `NoService` VARCHAR(255) NULL,
  `Advisor` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_TBLSUPPLIER_DATA` (
  `NoSupplier` VARCHAR(255) NULL,
  `NamaSupplier` VARCHAR(255) NULL,
  `Alamat` VARCHAR(255) NULL,
  `Kota` VARCHAR(255) NULL,
  `Propinsi` VARCHAR(255) NULL,
  `KodePost` VARCHAR(255) NULL,
  `Negara` VARCHAR(255) NULL,
  `Telephone` VARCHAR(255) NULL,
  `Fax` VARCHAR(255) NULL,
  `NamaBank` VARCHAR(255) NULL,
  `NoAccount` VARCHAR(255) NULL,
  `AtasNama` VARCHAR(255) NULL,
  `KontakPerson` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Note` LONGTEXT NULL,
  `SaldoAwal` DOUBLE NULL,
  `PerTanggal` DATETIME NULL,
  `JmlBayar` DOUBLE NULL,
  `Sisa` DOUBLE NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GABUNG_TBLUSER_DATA` (
  `USERID` VARCHAR(255) NULL,
  `NAMAUSER` VARCHAR(255) NULL,
  `PASSWORD` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `INSENTIF_JUAL_SERVIS_DATA` (
  `SIKLUS` VARCHAR(255) NULL,
  `TGL` DATETIME NULL,
  `TRX` VARCHAR(255) NULL,
  `GARAP` DOUBLE NULL,
  `STTS` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `KODE` VARCHAR(255) NULL,
  `MEKANIK` VARCHAR(255) NULL,
  `TIPE` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `Quantity` DOUBLE NULL,
  `JUALNET` DOUBLE NULL,
  `TOTHPP` DOUBLE NULL,
  `LABA` DOUBLE NULL,
  `KATEGORI` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `INSENTIF_JUAL_SERVIS_GABUNG_DATA` (
  `SIKLUS` VARCHAR(255) NULL,
  `TGL` DATETIME NULL,
  `TRX` VARCHAR(255) NULL,
  `GARAP` DOUBLE NULL,
  `STTS` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `KODE` VARCHAR(255) NULL,
  `MEKANIK` VARCHAR(255) NULL,
  `TIPE` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `Quantity` DOUBLE NULL,
  `JUALNET` DOUBLE NULL,
  `TOTHPP` DOUBLE NULL,
  `LABA` DOUBLE NULL,
  `KATEGORI` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `KENDARAAN_PELANGGAN_GABUNG_DATA` (
  `NoPolisi` VARCHAR(255) NULL,
  `NamaPelanggan` VARCHAR(255) NULL,
  `Merek` VARCHAR(255) NULL,
  `Tipe` VARCHAR(255) NULL,
  `Jenis` VARCHAR(255) NULL,
  `Warna` VARCHAR(255) NULL,
  `TahunBuat` VARCHAR(255) NULL,
  `Telephone` VARCHAR(255) NULL,
  `Grup` VARCHAR(255) NULL,
  `Alamat` VARCHAR(255) NULL,
  `Note` LONGTEXT NULL,
  `KATEGORI` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `Kota` VARCHAR(255) NULL,
  `KontakPerson` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LABARUGI_ACUAN_HPP_PEMBELIAN_TEMP` (
  `TAHUN` VARCHAR(255) NULL,
  `SIKLUS` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `FREK` INT NULL,
  `QTY` DOUBLE NULL,
  `BELI` DOUBLE NULL,
  `ACUAN_HPP` DOUBLE NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LABARUGI_ACUAN_QTY_ITEMKELUAR_TEMP` (
  `TAHUN` VARCHAR(255) NULL,
  `SIKLUS` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `FREK` INT NULL,
  `QTY` DOUBLE NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LABARUGI_ACUAN_QTY_ITEMMASUK_TEMP` (
  `TAHUN` VARCHAR(255) NULL,
  `SIKLUS` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `FREK` INT NULL,
  `QTY` DOUBLE NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LABARUGI_ACUAN_QTY_PENJUALAN_TEMP` (
  `TAHUN` VARCHAR(255) NULL,
  `SIKLUS` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `FREK` INT NULL,
  `QTY` DOUBLE NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LABARUGI_ACUAN_QTY_SERVIS_TEMP` (
  `TAHUN` VARCHAR(255) NULL,
  `SIKLUS` VARCHAR(255) NULL,
  `NoItem` VARCHAR(255) NULL,
  `FREK` INT NULL,
  `QTY` DOUBLE NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NOMOR_WA_GCONTACT_SEMUA_DATA` (
  `Given Name` VARCHAR(255) NULL,
  `Additional Name` VARCHAR(255) NULL,
  `Family Name` VARCHAR(255) NULL,
  `Group Membership` VARCHAR(255) NULL,
  `Phone 1 - Type` VARCHAR(255) NULL,
  `Phone 1 - Value` VARCHAR(255) NULL,
  `AKHIR` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NOMOR_WA__DOMISILI_POLISI_DATA` (
  `NamaPelanggan` VARCHAR(255) NULL,
  `Telephone` VARCHAR(255) NULL,
  `NoPelanggan` VARCHAR(255) NULL,
  `DOMISILI` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NOPOLISI_DOMISILI_DATA` (
  `NoPolisi` VARCHAR(255) NULL,
  `STS_PES` DOUBLE NULL,
  `STS_PAC` DOUBLE NULL,
  `STS_CIK` DOUBLE NULL,
  `STS_TRA` DOUBLE NULL,
  `AKHIR` DATETIME NULL,
  `STS` VARCHAR(255) NULL,
  `DOMISILI` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PEMBELIAN_PERITEM_PERSUPLIER_1_2_TEMP` (
  `NOITEM` VARCHAR(255) NULL,
  `SUPPLIER1` VARCHAR(255) NULL,
  `SUPPLIER2` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PERNAH_JEMPUTANTAR_DATA` (
  `NoPolisi` VARCHAR(255) NULL,
  `JUMLAH` INT NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PERSEN_INSENTIF` (
  `POSISI` VARCHAR(255) NULL,
  `PERSEN_BARANG` DECIMAL(19,4) NULL,
  `PERSEN_JASA` DECIMAL(19,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKAP_JUALSERVIS_PERITEM_TERAKHIR_DATA` (
  `TGGL` DATETIME NULL,
  `NoItem` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKAP_KONSUMEN_DATA` (
  `NoPolisi` VARCHAR(255) NULL,
  `JUMLAH` INT NULL,
  `AWAL` DATETIME NULL,
  `AKHIR` DATETIME NULL,
  `PELANGGAN_SEJAK_HARI` DOUBLE NULL,
  `PELANGGAN_SEJAK_BULAN` DOUBLE NULL,
  `LAMA_TDK_DTG_HARI` DOUBLE NULL,
  `LAMA_TDK_DTG_BULAN` DOUBLE NULL,
  `TOTAL` DOUBLE NULL,
  `RATA2` DOUBLE NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKAP_KONSUMEN_DATANGBERIKUTNYA_DATA` (
  `NoPolisi` VARCHAR(255) NULL,
  `JUMLAH` INT NULL,
  `AWAL` DATETIME NULL,
  `AKHIR` DATETIME NULL,
  `PELANGGAN_SEJAK_HARI` DOUBLE NULL,
  `PELANGGAN_SEJAK_BULAN` DOUBLE NULL,
  `LAMA_TDK_DTG_HARI` DOUBLE NULL,
  `LAMA_TDK_DTG_BULAN` DOUBLE NULL,
  `TOTAL` DOUBLE NULL,
  `RATA2` DOUBLE NULL,
  `GANTI_OLI_AKHIR` DATETIME NULL,
  `SERVIS_AKHIR` DATETIME NULL,
  `DATANG_BERIKUTNYA` DATETIME NULL,
  `REMIND_SEBELUMNYA` DATETIME NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKAP_KONSUMEN_NOMOR_WA_DATA` (
  `NamaPelanggan` VARCHAR(255) NULL,
  `DOMISILI` VARCHAR(255) NULL,
  `JUM_MOTOR` INT NULL,
  `TOT_DATANG` DOUBLE NULL,
  `TOTAL_NILAI` DOUBLE NULL,
  `RATA2_NILAI` DOUBLE NULL,
  `AWAL` DATETIME NULL,
  `AKHIR` DATETIME NULL,
  `DATANG_BERIKUTNYA` DATETIME NULL,
  `LAMA_PELANGGAN` DOUBLE NULL,
  `LAMA_TDK_DATANG` DOUBLE NULL,
  `TIAP_30HARI` DATETIME NULL,
  `Telephone` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `REKONSIL_JUAL_BELI_ANTARCABANG_DATA` (
  `CABANG` VARCHAR(255) NULL,
  `TANGGAL` DATETIME NULL,
  `KODE_JUAL` VARCHAR(255) NULL,
  `NAMA_JUAL` VARCHAR(255) NULL,
  `TIPE_JUAL` VARCHAR(255) NULL,
  `KATEGORI_JUAL` VARCHAR(255) NULL,
  `NO_JUAL` VARCHAR(255) NULL,
  `ITEM_JUAL` VARCHAR(255) NULL,
  `QTY_JUAL` DOUBLE NULL,
  `HPP_JUAL` DOUBLE NULL,
  `NILAI_JUAL` DOUBLE NULL,
  `SUMBER` VARCHAR(255) NULL,
  `KODE_BELI` VARCHAR(255) NULL,
  `NAMA_BELI` VARCHAR(255) NULL,
  `TIPE_BELI` VARCHAR(255) NULL,
  `KATEGORI_BELI` VARCHAR(255) NULL,
  `NO_BELI` VARCHAR(255) NULL,
  `ITEM_BELI` VARCHAR(255) NULL,
  `QTY_BELI` DOUBLE NULL,
  `HPP_BELI` DOUBLE NULL,
  `NILAI_BELI` DOUBLE NULL,
  `ID_BELI` VARCHAR(255) NULL,
  `tanggal_data` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `STOK_OPNAM_TEMP` (
  `NO` VARCHAR(255) NULL,
  `RAK` VARCHAR(255) NULL,
  `KODE` VARCHAR(255) NULL,
  `NAMA` VARCHAR(255) NULL,
  `STOK` VARCHAR(255) NULL,
  `NOTE` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `STOK_OPNAM_TES` (
  `RAK` VARCHAR(255) NULL,
  `KODE` VARCHAR(255) NULL,
  `NAMA` VARCHAR(255) NULL,
  `STOK` VARCHAR(255) NULL,
  `NOTE` VARCHAR(255) NULL,
  `STS` VARCHAR(255) NULL,
  `CABANG` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `STOK_OPNAM_TIDAKLAKU` (
  `TANGGAL_AWAL` DATETIME NULL,
  `TANGGAL` DATETIME NULL,
  `NOITEM` VARCHAR(255) NULL,
  `Nama` VARCHAR(255) NULL,
  `QTY_SAL` DOUBLE NULL,
  `QTY_CUL` DOUBLE NULL,
  `TOTAL_STOK` DOUBLE NULL,
  `RAK_SAL` VARCHAR(255) NULL,
  `RAK_CUL` VARCHAR(255) NULL,
  `STATUSSAL` VARCHAR(255) NULL,
  `STATUSCUL` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Switchboard Items` (
  `SwitchboardID` INT NULL,
  `ItemNumber` SMALLINT NULL,
  `ItemText` VARCHAR(255) NULL,
  `Command` SMALLINT NULL,
  `Argument` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TBLCABANG` (
  `KODE` VARCHAR(255) NULL,
  `CABANG` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;