-- Import master keluhan dari data Access FITMOTOR GABUNG
-- Generated: 2026-06-19 | Total: 102 keluhan

START TRANSACTION;

-- Hapus data test/sampah
DELETE FROM tbmaster_keluhan WHERE id IN (16,17,18,19,20);

-- Hapus duplikat
DELETE FROM tbmaster_keluhan WHERE kode_keluhan IN ('KEL009','KEL011','KEL015');

-- Insert keluhan nyata dari data lapangan 4 cabang
INSERT INTO tbmaster_keluhan (kode_keluhan, nama_keluhan, kategori, status_aktif, status_approval, tingkat_prioritas, created_at) VALUES
('KEL024','Ganti Oli Mesin','Ganti Oli','1','approved','Sedang',NOW()),
('KEL025','Servis Standar','Servis Rutin','1','approved','Sedang',NOW()),
('KEL026','Tune Up','Servis Rutin','1','approved','Sedang',NOW()),
('KEL027','Servis Cvt','CVT','1','approved','Sedang',NOW()),
('KEL028','Servis Rutin','Servis Rutin','1','approved','Sedang',NOW()),
('KEL029','Mogok','Mesin','1','approved','Tinggi',NOW()),
('KEL030','Ganti Oli Gear','Ganti Oli','1','approved','Sedang',NOW()),
('KEL031','Tarikan Berat','Mesin','1','approved','Sedang',NOW()),
('KEL032','Ganti Oli Gardan','Ganti Oli','1','approved','Sedang',NOW()),
('KEL033','Ganti Aki','Kelistrikan','1','approved','Sedang',NOW()),
('KEL034','Ganti Lampu Depan','Kelistrikan','1','approved','Sedang',NOW()),
('KEL035','Lampu Depan Mati','Kelistrikan','1','approved','Sedang',NOW()),
('KEL036','Cek Oli Gear','Ganti Oli','1','approved','Normal',NOW()),
('KEL037','Ganti Kampas Belakang','Umum','1','approved','Normal',NOW()),
('KEL038','Perawatan Cvt','CVT','1','approved','Normal',NOW()),
('KEL039','Cek Rem','Rem','1','approved','Normal',NOW()),
('KEL040','Ganti Kampas Depan','Umum','1','approved','Normal',NOW()),
('KEL041','Stater Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL042','Servis Full','Servis Rutin','1','approved','Normal',NOW()),
('KEL043','Ganti Komstir','Suspensi','1','approved','Normal',NOW()),
('KEL044','Rem Kurang Pakem','Rem','1','approved','Normal',NOW()),
('KEL045','Mbrebet','Mesin','1','approved','Normal',NOW()),
('KEL046','Cek Aki','Kelistrikan','1','approved','Normal',NOW()),
('KEL047','Ganti Bohlam Depan','Kelistrikan','1','approved','Normal',NOW()),
('KEL048','Suara Kasar','Mesin','1','approved','Normal',NOW()),
('KEL049','Cek Komstir','Suspensi','1','approved','Normal',NOW()),
('KEL050','Gas Berat','Mesin','1','approved','Normal',NOW()),
('KEL051','Ganti Busi','Mesin','1','approved','Normal',NOW()),
('KEL052','Ganti Ban Dalam Belakang','Ban','1','approved','Normal',NOW()),
('KEL053','Ganti Ban Luar Belakang','Ban','1','approved','Normal',NOW()),
('KEL054','Stater Susah','Kelistrikan','1','approved','Normal',NOW()),
('KEL055','Lampu Belakang Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL056','Stang Berat','Suspensi','1','approved','Normal',NOW()),
('KEL057','Strum Aki','Kelistrikan','1','approved','Normal',NOW()),
('KEL058','Cek Oli Gardan','Ganti Oli','1','approved','Normal',NOW()),
('KEL059','Ganti Fanbelt','Transmisi','1','approved','Normal',NOW()),
('KEL060','Cek Air Radiator','Pendingin','1','approved','Normal',NOW()),
('KEL061','Klakson Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL062','Ganti Girset','Transmisi','1','approved','Normal',NOW()),
('KEL063','Bensin Boros','Umum','1','approved','Normal',NOW()),
('KEL064','Gurah Mesin','Servis Rutin','1','approved','Normal',NOW()),
('KEL065','Speedometer Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL066','Ganti Ban Luar Depan','Ban','1','approved','Normal',NOW()),
('KEL067','Cek Oli Mesin','Ganti Oli','1','approved','Normal',NOW()),
('KEL068','Bagian Belakang Bunyi','Umum','1','approved','Normal',NOW()),
('KEL069','Setel Rantai','Transmisi','1','approved','Normal',NOW()),
('KEL070','Stang Tempang','Suspensi','1','approved','Normal',NOW()),
('KEL071','Turun Mesin','Mesin','1','approved','Normal',NOW()),
('KEL072','Ganti Ban Tubles Belakang','Ban','1','approved','Normal',NOW()),
('KEL073','Cvt Bunyi','CVT','1','approved','Normal',NOW()),
('KEL074','Tarikan Biar Enteng','Mesin','1','approved','Normal',NOW()),
('KEL075','Ganti Lampu Belakang','Kelistrikan','1','approved','Normal',NOW()),
('KEL076','Ganti Master Rem','Rem','1','approved','Normal',NOW()),
('KEL077','Ganti Laher Depan','Suspensi','1','approved','Normal',NOW()),
('KEL078','Ganti Roller','CVT','1','approved','Normal',NOW()),
('KEL079','Spedometer Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL080','Bagian Depan Bunyi','Umum','1','approved','Normal',NOW()),
('KEL081','Cek Kampas Belakang','Umum','1','approved','Normal',NOW()),
('KEL082','Rem Belakang Bunyi','Rem','1','approved','Normal',NOW()),
('KEL083','Ganti Filter Udara','Filter','1','approved','Normal',NOW()),
('KEL084','Paket Servis Gratis Gurah','Servis Rutin','1','approved','Normal',NOW()),
('KEL085','Stel Komstir','Suspensi','1','approved','Normal',NOW()),
('KEL086','Servis Standar/Cvt/Gurah','CVT','1','approved','Normal',NOW()),
('KEL087','Riting Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL088','Stel Rante','Transmisi','1','approved','Normal',NOW()),
('KEL089','Isi Air Radiator','Pendingin','1','approved','Normal',NOW()),
('KEL090','Ganti Kampas Ganda','CVT','1','approved','Normal',NOW()),
('KEL091','Lampu Jarak Pendek Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL092','Kilometer Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL093','Ganti Spion','Body','1','approved','Normal',NOW()),
('KEL094','Cek Lampu','Kelistrikan','1','approved','Normal',NOW()),
('KEL095','Rem Depan Blong','Rem','1','approved','Normal',NOW()),
('KEL096','Tarikannya Berat','Mesin','1','approved','Normal',NOW()),
('KEL097','Oli Rembes','Rem','1','approved','Normal',NOW()),
('KEL098','Rante Kendor','Transmisi','1','approved','Normal',NOW()),
('KEL099','Ganti Bohlam Belakang','Kelistrikan','1','approved','Normal',NOW()),
('KEL100','Pasang Spion','Body','1','approved','Normal',NOW()),
('KEL101','Ngga Bisa Distater','Kelistrikan','1','approved','Normal',NOW()),
('KEL102','Gak Bisa Distater','Kelistrikan','1','approved','Normal',NOW()),
('KEL103','Cek Cvt','CVT','1','approved','Normal',NOW()),
('KEL104','Lampu Rem Mati','Rem','1','approved','Normal',NOW()),
('KEL105','Setel Komstir','Suspensi','1','approved','Normal',NOW()),
('KEL106','Tarikan Kurang','Mesin','1','approved','Normal',NOW()),
('KEL107','Km Mati','Umum','1','approved','Normal',NOW()),
('KEL108','Oli Bocor','Mesin','1','approved','Normal',NOW()),
('KEL109','Cek Kampas Depan','Umum','1','approved','Normal',NOW()),
('KEL110','Gas Ngempos','Mesin','1','approved','Normal',NOW()),
('KEL111','Cek Kelistrikan','Kelistrikan','1','approved','Normal',NOW()),
('KEL112','Cek Fanbelt','Transmisi','1','approved','Normal',NOW()),
('KEL113','Ganti Air Radiator','Pendingin','1','approved','Normal',NOW()),
('KEL114','Kuras Radiator','Pendingin','1','approved','Normal',NOW()),
('KEL115','Bohlam Depan Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL116','Cek Busi','Mesin','1','approved','Normal',NOW()),
('KEL117','Rantai Kendor','Transmisi','1','approved','Normal',NOW()),
('KEL118','Ganti Ban Tubles Depan','Ban','1','approved','Normal',NOW()),
('KEL119','Setel Rante','Transmisi','1','approved','Normal',NOW()),
('KEL120','Cek Shock Depan','Suspensi','1','approved','Normal',NOW()),
('KEL121','Spidometer Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL122','Servis Lengkap','Servis Rutin','1','approved','Normal',NOW()),
('KEL123','Bensin Bocor','Mesin','1','approved','Normal',NOW()),
('KEL124','Speedo Mati','Kelistrikan','1','approved','Normal',NOW()),
('KEL125','Dicek Semua','Umum','1','approved','Normal',NOW());

COMMIT;
