-- ============================================================
-- SQL Script: Create Trigger for Auto-Update Statistik Pelanggan
-- ============================================================
-- 
-- Trigger ini akan otomatis update statistik_pelanggan
-- setiap kali ada service yang status_servis berubah ke 'bayar'
--
-- INSTRUKSI:
-- 1. Jalankan script ini di phpMyAdmin atau MySQL CLI
-- 2. Pilih database: fitmotor_dbbengkel
-- 3. Execute script
--
-- @author Generated by AI Assistant  
-- @date 2025-12-22
-- ============================================================

-- Drop existing trigger if exists
DROP TRIGGER IF EXISTS trg_update_statistik_after_payment;

-- Create the trigger
DELIMITER //

CREATE TRIGGER trg_update_statistik_after_payment
AFTER UPDATE ON tblservice
FOR EACH ROW
BEGIN
    -- Variabel untuk menyimpan nilai kalkulasi
    DECLARE v_total_transaksi INT DEFAULT 0;
    DECLARE v_total_nominal DECIMAL(15,2) DEFAULT 0;
    DECLARE v_rata_rata DECIMAL(15,2) DEFAULT 0;
    DECLARE v_total_motor INT DEFAULT 0;
    DECLARE v_tanggal_pertama DATE;
    DECLARE v_tanggal_terakhir DATE;
    DECLARE v_tier VARCHAR(50) DEFAULT 'Bronze';
    DECLARE v_lama_tidak_datang INT DEFAULT 0;
    
    -- Hanya proses jika status berubah ke 'bayar'
    IF NEW.status_servis = 'bayar' AND OLD.status_servis != 'bayar' THEN
        
        -- Hitung statistik dari semua transaksi bayar pelanggan ini
        SELECT 
            COUNT(*),
            COALESCE(SUM(IFNULL(total_akhir, IFNULL(total_grand, IFNULL(total, 0)))), 0),
            MIN(tanggal),
            MAX(tanggal),
            COUNT(DISTINCT no_polisi)
        INTO 
            v_total_transaksi,
            v_total_nominal,
            v_tanggal_pertama,
            v_tanggal_terakhir,
            v_total_motor
        FROM tblservice
        WHERE no_pelanggan = NEW.no_pelanggan
          AND status_servis = 'bayar';
        
        -- Hitung rata-rata
        IF v_total_transaksi > 0 THEN
            SET v_rata_rata = v_total_nominal / v_total_transaksi;
        END IF;
        
        -- Determine member tier berdasarkan nominal
        IF v_total_nominal >= 10000000 THEN
            SET v_tier = 'Platinum';
        ELSEIF v_total_nominal >= 5000000 THEN
            SET v_tier = 'Gold';
        ELSEIF v_total_nominal >= 2000000 THEN
            SET v_tier = 'Silver';
        ELSE
            SET v_tier = 'Bronze';
        END IF;
        
        -- Hitung lama tidak datang
        SET v_lama_tidak_datang = DATEDIFF(CURDATE(), v_tanggal_terakhir);
        
        -- UPSERT ke statistik_pelanggan
        INSERT INTO statistik_pelanggan (
            no_pelanggan,
            total_transaksi,
            total_nominal,
            jumlah_kunjungan,
            kedatangan_terakhir,
            rata_rata_transaksi,
            status_member,
            tanggal_pertama_transaksi,
            tanggal_terakhir_transaksi,
            total_motor,
            lama_tidak_datang
        ) VALUES (
            NEW.no_pelanggan,
            v_total_transaksi,
            v_total_nominal,
            v_total_transaksi,
            v_total_transaksi,
            v_rata_rata,
            v_tier,
            v_tanggal_pertama,
            v_tanggal_terakhir,
            v_total_motor,
            v_lama_tidak_datang
        ) ON DUPLICATE KEY UPDATE
            total_transaksi = v_total_transaksi,
            total_nominal = v_total_nominal,
            jumlah_kunjungan = v_total_transaksi,
            kedatangan_terakhir = v_total_transaksi,
            rata_rata_transaksi = v_rata_rata,
            status_member = v_tier,
            tanggal_pertama_transaksi = v_tanggal_pertama,
            tanggal_terakhir_transaksi = v_tanggal_terakhir,
            total_motor = v_total_motor,
            lama_tidak_datang = v_lama_tidak_datang,
            updated_at = NOW();
            
    END IF;
    
END//

DELIMITER ;

-- ============================================================
-- Verification: Check if trigger was created
-- ============================================================
SHOW TRIGGERS LIKE 'tblservice';

-- ============================================================
-- Test Query (optional - uncomment to test)
-- ============================================================
-- SELECT * FROM statistik_pelanggan ORDER BY updated_at DESC LIMIT 5;
