<?php
/**
 * Migration Script: Populate statistik_pelanggan dari data historis
 * 
 * Script ini menghitung ulang statistik pelanggan dari data tblservice
 * yang sudah status 'bayar' dan mengupdate tabel statistik_pelanggan.
 * 
 * INSTRUKSI PENGGUNAAN:
 * 1. Jalankan script ini SEKALI untuk migrasi data lama
 * 2. Akses via browser: http://localhost/web-bengkel/aplikasi/aplikasi/_admincab/migrate_statistik_pelanggan.php
 * 3. Atau via CLI: php migrate_statistik_pelanggan.php
 * 
 * @author Generated by AI Assistant
 * @date 2025-12-22
 */

// Untuk akses via CLI atau Browser
if (php_sapi_name() !== 'cli') {
    session_start();
}

// Include koneksi database
$basePath = __DIR__ . '/../';
if (file_exists($basePath . 'config/koneksi.php')) {
    require_once $basePath . 'config/koneksi.php';
} elseif (file_exists('../config/koneksi.php')) {
    require_once '../config/koneksi.php';
}

// Include statistik helper
if (file_exists('_include_statistik_pelanggan.php')) {
    require_once '_include_statistik_pelanggan.php';
}

// Security check untuk browser access (opsional - hapus jika tidak perlu)
if (php_sapi_name() !== 'cli') {
    if (empty($_SESSION['_iduser'])) {
        die("Akses ditolak. Silakan login terlebih dahulu.");
    }
}

echo "<html><head><title>Migrasi Statistik Pelanggan</title>";
echo "<style>
body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
.container { max-width: 1200px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
.success { background: #d4edda; color: #155724; padding: 10px; border-radius: 4px; margin: 5px 0; }
.error { background: #f8d7da; color: #721c24; padding: 10px; border-radius: 4px; margin: 5px 0; }
.warning { background: #fff3cd; color: #856404; padding: 10px; border-radius: 4px; margin: 5px 0; }
.info { background: #d1ecf1; color: #0c5460; padding: 10px; border-radius: 4px; margin: 5px 0; }
table { width: 100%; border-collapse: collapse; margin: 20px 0; }
th, td { padding: 10px; text-align: left; border: 1px solid #ddd; }
th { background: #667eea; color: #fff; }
tr:nth-child(even) { background: #f9f9f9; }
h1 { color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
.btn { display: inline-block; padding: 10px 20px; background: #667eea; color: #fff; text-decoration: none; border-radius: 5px; margin-top: 20px; }
.btn:hover { background: #5a6dc9; }
pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
</style></head><body>";

echo "<div class='container'>";
echo "<h1>🔄 Migrasi Statistik Pelanggan</h1>";

// ============================================================
// STEP 1: Cek koneksi database
// ============================================================
if (!isset($koneksi) || !$koneksi) {
    die("<div class='error'>❌ Koneksi database gagal!</div></body></html>");
}
echo "<div class='success'>✅ Koneksi database berhasil</div>";

// ============================================================
// STEP 2: Ambil semua pelanggan unik yang pernah service
// ============================================================
$query_pelanggan = "SELECT DISTINCT 
                        s.no_pelanggan,
                        p.namapelanggan
                    FROM tblservice s
                    LEFT JOIN tblpelanggan p ON s.no_pelanggan = p.nopelanggan
                    WHERE s.no_pelanggan IS NOT NULL 
                      AND s.no_pelanggan != ''
                    ORDER BY s.no_pelanggan";

$result_pelanggan = mysqli_query($koneksi, $query_pelanggan);

if (!$result_pelanggan) {
    die("<div class='error'>❌ Gagal mengambil data pelanggan: " . mysqli_error($koneksi) . "</div></body></html>");
}

$total_pelanggan = mysqli_num_rows($result_pelanggan);
echo "<div class='info'>📊 Ditemukan <strong>{$total_pelanggan}</strong> pelanggan unik yang pernah service</div>";

// ============================================================
// STEP 3: Loop dan update statistik setiap pelanggan
// ============================================================
$berhasil = 0;
$gagal = 0;
$skipped = 0;
$log_results = [];

echo "<h2>📝 Progress Migrasi</h2>";
echo "<table>";
echo "<thead><tr><th>No</th><th>No Pelanggan</th><th>Nama</th><th>Total Transaksi</th><th>Total Nominal</th><th>Status</th></tr></thead>";
echo "<tbody>";

$counter = 0;
while ($row = mysqli_fetch_assoc($result_pelanggan)) {
    $counter++;
    $no_pelanggan = $row['no_pelanggan'];
    $nama_pelanggan = $row['namapelanggan'] ?? '-';
    
    // Hitung statistik dari tblservice
    $query_stats = "SELECT 
                        COUNT(*) as total_transaksi,
                        COALESCE(SUM(IFNULL(total_akhir, IFNULL(total_grand, IFNULL(total, 0)))), 0) as total_nominal,
                        MIN(tanggal) as tanggal_pertama,
                        MAX(tanggal) as tanggal_terakhir,
                        COUNT(DISTINCT no_polisi) as total_motor
                    FROM tblservice 
                    WHERE no_pelanggan = '$no_pelanggan' 
                      AND status_servis = 'bayar'";
    
    $result_stats = mysqli_query($koneksi, $query_stats);
    
    if (!$result_stats) {
        $gagal++;
        echo "<tr class='error'><td>{$counter}</td><td>{$no_pelanggan}</td><td>{$nama_pelanggan}</td><td colspan='3'>Error: " . mysqli_error($koneksi) . "</td></tr>";
        continue;
    }
    
    $stats = mysqli_fetch_assoc($result_stats);
    $total_transaksi = intval($stats['total_transaksi']);
    $total_nominal = floatval($stats['total_nominal']);
    
    // Skip jika tidak ada transaksi bayar
    if ($total_transaksi == 0) {
        $skipped++;
        continue;
    }
    
    // Gunakan function yang sudah ada jika available
    if (function_exists('updateStatistikPelangganAfterPayment')) {
        $success = updateStatistikPelangganAfterPayment($koneksi, $no_pelanggan, 'MIGRATION');
    } else {
        // Fallback manual upsert
        $rata_rata = $total_transaksi > 0 ? $total_nominal / $total_transaksi : 0;
        
        // Determine tier
        $tier = 'Bronze';
        if ($total_nominal >= 10000000) $tier = 'Platinum';
        elseif ($total_nominal >= 5000000) $tier = 'Gold';
        elseif ($total_nominal >= 2000000) $tier = 'Silver';
        
        $no_pelanggan_esc = mysqli_real_escape_string($koneksi, $no_pelanggan);
        
        $query_upsert = "INSERT INTO statistik_pelanggan (
                            no_pelanggan, total_transaksi, total_nominal, 
                            jumlah_kunjungan, rata_rata_transaksi, status_member,
                            total_motor, tanggal_pertama_transaksi, tanggal_terakhir_transaksi
                        ) VALUES (
                            '$no_pelanggan_esc', {$total_transaksi}, {$total_nominal},
                            {$total_transaksi}, {$rata_rata}, '$tier',
                            {$stats['total_motor']}, '{$stats['tanggal_pertama']}', '{$stats['tanggal_terakhir']}'
                        ) ON DUPLICATE KEY UPDATE
                            total_transaksi = {$total_transaksi},
                            total_nominal = {$total_nominal},
                            jumlah_kunjungan = {$total_transaksi},
                            rata_rata_transaksi = {$rata_rata},
                            status_member = '$tier',
                            total_motor = {$stats['total_motor']},
                            tanggal_pertama_transaksi = '{$stats['tanggal_pertama']}',
                            tanggal_terakhir_transaksi = '{$stats['tanggal_terakhir']}'";
        
        $success = mysqli_query($koneksi, $query_upsert);
    }
    
    if ($success) {
        $berhasil++;
        $status_badge = "<span style='color: green;'>✅ Berhasil</span>";
    } else {
        $gagal++;
        $status_badge = "<span style='color: red;'>❌ Gagal</span>";
    }
    
    echo "<tr>";
    echo "<td>{$counter}</td>";
    echo "<td>{$no_pelanggan}</td>";
    echo "<td>{$nama_pelanggan}</td>";
    echo "<td>{$total_transaksi}x</td>";
    echo "<td>Rp " . number_format($total_nominal, 0, ',', '.') . "</td>";
    echo "<td>{$status_badge}</td>";
    echo "</tr>";
    
    // Flush output untuk progress realtime
    if (ob_get_level() > 0) {
        ob_flush();
    }
    flush();
}

echo "</tbody></table>";

// ============================================================
// STEP 4: Summary
// ============================================================
echo "<h2>📊 Ringkasan Migrasi</h2>";
echo "<div class='info'>";
echo "<strong>Total Pelanggan:</strong> {$total_pelanggan}<br>";
echo "<strong>Berhasil Dimigrasi:</strong> <span style='color: green;'>{$berhasil}</span><br>";
echo "<strong>Gagal:</strong> <span style='color: red;'>{$gagal}</span><br>";
echo "<strong>Dilewati (tanpa transaksi bayar):</strong> {$skipped}<br>";
echo "</div>";

if ($gagal == 0 && $berhasil > 0) {
    echo "<div class='success'><strong>🎉 Migrasi selesai dengan sukses!</strong></div>";
} elseif ($gagal > 0) {
    echo "<div class='warning'><strong>⚠️ Migrasi selesai dengan beberapa error</strong></div>";
}

echo "<a href='index.php' class='btn'>← Kembali ke Dashboard</a>";
echo "</div></body></html>";
?>
