import json

# Read analysis files
with open('database_categorization.json', 'r', encoding='utf-8') as f:
    categorization = json.load(f)

with open('table_analysis.json', 'r', encoding='utf-8') as f:
    tables = json.load(f)

with open('naming_analysis.json', 'r', encoding='utf-8') as f:
    naming = json.load(f)

with open('database_relationships.json', 'r', encoding='utf-8') as f:
    relationships = json.load(f)

# Generate executive summary
output = []
output.append("=" * 80)
output.append("DATABASE ANALYSIS EXECUTIVE SUMMARY")
output.append("FITMOTOR BENGKEL MANAGEMENT SYSTEM")
output.append("=" * 80)
output.append("")
output.append("Generated: 2025-11-28")
output.append("")
output.append("=" * 80)
output.append("OVERVIEW")
output.append("=" * 80)
output.append("")
output.append(f"Total Tables:                    {categorization['total_tables']}")
output.append(f"Master Data Tables:              {categorization['categories']['Master Data']}")
output.append(f"Transaction Tables:              {categorization['categories']['Transaksi']}")
output.append(f"System & Configuration Tables:   {categorization['categories']['System & Configuration']}")
output.append(f"Views:                           {categorization['categories']['Views']}")
output.append(f"Lookup/Reference Tables:         {categorization['categories']['Lookup/Reference']}")
output.append("")

output.append("=" * 80)
output.append("KEY METRICS")
output.append("=" * 80)
output.append("")
output.append(f"Tables with Primary Keys:        {categorization['total_tables'] - len(naming['design_issues']['no_primary_key'])}")
output.append(f"Tables WITHOUT Primary Keys:     {len(naming['design_issues']['no_primary_key'])} (CRITICAL)")
output.append(f"Tables with Timestamps:          {categorization['total_tables'] - len(naming['design_issues']['missing_timestamps'])}")
output.append(f"Tables WITHOUT Timestamps:       {len(naming['design_issues']['missing_timestamps'])}")
output.append(f"Header-Detail Pairs:             {len(relationships['header_detail_pairs'])}")
output.append("")

output.append("=" * 80)
output.append("NAMING CONVENTION BREAKDOWN")
output.append("=" * 80)
output.append("")
for prefix, count in sorted(naming['naming_patterns'].items(), key=lambda x: x[1], reverse=True):
    if count > 0:
        output.append(f"{prefix:20s} {count:3d} tables")
output.append("")

output.append("=" * 80)
output.append("TOP 10 LARGEST TABLES (by column count)")
output.append("=" * 80)
output.append("")

# Get largest tables
table_sizes = [(name, len(data['columns'])) for name, data in tables.items() if not name.startswith('view_')]
table_sizes.sort(key=lambda x: x[1], reverse=True)

for i, (table, col_count) in enumerate(table_sizes[:10], 1):
    output.append(f"{i:2d}. {table:50s} {col_count:3d} columns")

output.append("")

output.append("=" * 80)
output.append("CRITICAL TABLES (Core Operations)")
output.append("=" * 80)
output.append("")
output.append("Customer & Vehicle Management:")
output.append("  - tblpelanggan        (Customer master)")
output.append("  - tblkendaraan        (Vehicle registration)")
output.append("")
output.append("Service Management:")
output.append("  - tblservice          (Service transactions)")
output.append("  - tblservis_barang    (Service parts)")
output.append("  - tblservis_jasa      (Service labor)")
output.append("  - tbservis_keluhan    (Complaints)")
output.append("  - tbservis_temuan     (Findings)")
output.append("  - tbservis_workorder  (Work orders)")
output.append("")
output.append("Inventory Management:")
output.append("  - tblitem             (Product master)")
output.append("  - tblitem_stok        (Stock levels)")
output.append("  - tbstok              (Stock transactions)")
output.append("")
output.append("Sales & Purchase:")
output.append("  - tblpenjualan_header (Sales header)")
output.append("  - tblpenjualan_detail (Sales detail)")
output.append("  - tblpembelian_header (Purchase header)")
output.append("  - tblpembelian_detail (Purchase detail)")
output.append("")
output.append("Procurement:")
output.append("  - tblpurchase_request_header (PR header)")
output.append("  - tblorder_header            (PO header)")
output.append("  - tbldelivery_order_header   (DO header)")
output.append("")

output.append("=" * 80)
output.append("CRITICAL ISSUES SUMMARY")
output.append("=" * 80)
output.append("")
output.append("PRIORITY 1 - CRITICAL:")
output.append(f"  [{len(naming['design_issues']['no_primary_key'])}] Tables without primary keys")
output.append("  [MANY] Missing foreign key constraints")
output.append("  [MANY] Missing indexes on FK columns")
output.append("")
output.append("PRIORITY 2 - HIGH:")
output.append(f"  [{len(naming['design_issues']['missing_timestamps'])}] Tables without timestamp columns")
output.append("  [YES] Inconsistent naming conventions")
output.append("  [YES] Missing audit trail columns")
output.append("")
output.append("PRIORITY 3 - MEDIUM:")
output.append(f"  [{len(naming['design_issues']['large_tables'])}] Tables with too many columns (>40)")
output.append("  [7] Backup tables in production database")
output.append("  [YES] Need for data normalization")
output.append("")

output.append("=" * 80)
output.append("MODULE COVERAGE")
output.append("=" * 80)
output.append("")
output.append("[X] Customer & Vehicle Management")
output.append("[X] Service Management (Full workflow)")
output.append("[X] Inventory Management")
output.append("[X] Sales & Purchase")
output.append("[X] Procurement Chain (PR -> PO -> DO)")
output.append("[X] Financial Management (AR/AP)")
output.append("[X] HR & Payroll")
output.append("[X] User Management & RBAC")
output.append("[X] Reporting (Views)")
output.append("[X] Audit & Logging")
output.append("")

output.append("=" * 80)
output.append("RECOMMENDED ACTIONS")
output.append("=" * 80)
output.append("")
output.append("IMMEDIATE (This Week):")
output.append("  1. Review and document all 50 tables without primary keys")
output.append("  2. Prioritize which tables need PKs most urgently")
output.append("  3. Create migration script for adding PKs")
output.append("")
output.append("SHORT TERM (1 Month):")
output.append("  4. Add primary keys to all critical transaction tables")
output.append("  5. Implement foreign key constraints for core relationships")
output.append("  6. Add indexes on frequently queried columns")
output.append("  7. Add created_at/updated_at to all tables")
output.append("")
output.append("MEDIUM TERM (3 Months):")
output.append("  8. Standardize naming conventions")
output.append("  9. Normalize large tables")
output.append("  10. Implement comprehensive audit logging")
output.append("  11. Clean up backup tables")
output.append("")
output.append("LONG TERM (6+ Months):")
output.append("  12. Performance optimization based on usage patterns")
output.append("  13. Implement data archival strategy")
output.append("  14. Consider partitioning large tables")
output.append("")

output.append("=" * 80)
output.append("DOCUMENTATION FILES")
output.append("=" * 80)
output.append("")
output.append("1. DATABASE_STRUCTURE_ANALYSIS.md  - Comprehensive analysis (660 lines)")
output.append("2. DATABASE_TABLE_LIST.txt         - Complete table catalog (1012 lines)")
output.append("3. DATABASE_ERD.txt                - Entity relationship diagrams (282 lines)")
output.append("4. DATABASE_ISSUES.txt             - Issues and recommendations (184 lines)")
output.append("5. EXECUTIVE_SUMMARY.txt           - This file")
output.append("")
output.append("Additional Analysis Files:")
output.append("  - table_analysis.json            - Raw table structure data")
output.append("  - database_categorization.json   - Table categorization")
output.append("  - database_relationships.json    - Relationship mapping")
output.append("  - naming_analysis.json           - Naming convention analysis")
output.append("  - important_tables_detail.json   - Detailed analysis of key tables")
output.append("")

output.append("=" * 80)
output.append("END OF SUMMARY")
output.append("=" * 80)

# Write to file
with open('EXECUTIVE_SUMMARY.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(output))

print("Generated EXECUTIVE_SUMMARY.txt")
print("")
print("=" * 60)
print("ALL DOCUMENTATION GENERATED SUCCESSFULLY")
print("=" * 60)
print("")
print("Files created:")
print("  1. DATABASE_STRUCTURE_ANALYSIS.md  (19 KB)")
print("  2. DATABASE_TABLE_LIST.txt         (40 KB)")
print("  3. DATABASE_ERD.txt                (15 KB)")
print("  4. DATABASE_ISSUES.txt             (8.3 KB)")
print("  5. EXECUTIVE_SUMMARY.txt           (NEW)")
print("")
print(f"Total Tables Analyzed: {categorization['total_tables']}")
print(f"Critical Issues Found: {len(naming['design_issues']['no_primary_key'])} tables without PK")
print("")
