import json

# Read analysis files
with open('database_relationships.json', 'r', encoding='utf-8') as f:
    relationships = json.load(f)

with open('table_analysis.json', 'r', encoding='utf-8') as f:
    tables = json.load(f)

# Generate DATABASE_ERD.txt
output = []
output.append("=" * 100)
output.append("DATABASE ERD (Entity Relationship Diagram) - FITMOTOR BENGKEL SYSTEM")
output.append("=" * 100)
output.append(f"Generated: 2025-11-28\n")
output.append("=" * 100)
output.append("\nLegend:")
output.append("  [PK] = Primary Key")
output.append("  [FK] = Foreign Key")
output.append("  1 ----< * = One to Many relationship")
output.append("  * >----< * = Many to Many relationship")
output.append("")

# Core Module: Customer & Vehicle Management
output.append("\n" + "=" * 100)
output.append("MODULE 1: CUSTOMER & VEHICLE MANAGEMENT")
output.append("=" * 100)
output.append("")
output.append("+-------------------------------------+")
output.append("|      TBLPELANGGAN (Customer)        |")
output.append("+-------------------------------------+")
output.append("| [PK] no_pelanggan                   |")
output.append("|      nama_pelanggan                 |")
output.append("|      alamat                         |")
output.append("|      telepon                        |")
output.append("|      hp                             |")
output.append("|      email                          |")
output.append("|      kategori                       |")
output.append("|      ... (35 columns total)         |")
output.append("+-------------------------------------+")
output.append("       |")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+-------------------------------------+")
output.append("|      TBLKENDARAAN (Vehicle)         |")
output.append("+-------------------------------------+")
output.append("| [PK] nopol                          |")
output.append("| [FK] no_pelanggan                   |")
output.append("|      kode_tipe                      |")
output.append("|      tahun                          |")
output.append("|      warna                          |")
output.append("|      no_rangka                      |")
output.append("|      no_mesin                       |")
output.append("|      ... (16 columns total)         |")
output.append("+-------------------------------------+")

# Service Module
output.append("\n\n" + "=" * 100)
output.append("MODULE 2: SERVICE MANAGEMENT")
output.append("=" * 100)
output.append("")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("|      TBLKENDARAAN                   |         |      TBLPELANGGAN                   |")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("       |                                                 |")
output.append("       | 1                                               | 1")
output.append("       |                                                 |")
output.append("       | *                                               | *")
output.append("       V                                                 V")
output.append("+-----------------------------------------------------------------------------------+")
output.append("|                    TBLSERVICE (Service Transaction Header)                        |")
output.append("+-----------------------------------------------------------------------------------+")
output.append("| [PK] no_service                                                                   |")
output.append("| [FK] no_pelanggan, nopol                                                          |")
output.append("|      tanggal, tanggal_keluar, tanggal_estimasi                                    |")
output.append("|      km, keluhan, saran, diagnosa                                                 |")
output.append("|      total_jasa, total_barang, total_akhir, ppn, diskon                           |")
output.append("|      status_bayar, status_service, jenis_service                                  |")
output.append("|      ... (68 columns total)                                                       |")
output.append("+-----------------------------------------------------------------------------------+")
output.append("       |")
output.append("       +------------+-----------+-------------+--------------+")
output.append("       | *          | *         | *           | *            | *")
output.append("       V            V           V             V              V")
output.append("+--------------+ +----------+ +------------+ +------------+ +--------------+")
output.append("| TBLSERVIS_   | | TBLSERVIS| | TBSERVIS_  | | TBSERVIS_  | | TBSERVIS_    |")
output.append("| BARANG       | | _JASA    | | KELUHAN    | | TEMUAN     | | WORKORDER    |")
output.append("+--------------+ +----------+ +------------+ +------------+ +--------------+")
output.append("| [PK] id      | |[PK] id   | |[PK] id     | |[PK] id     | |[PK] id       |")
output.append("| [FK] no_serv | |[FK] no_  | |[FK] no_    | |[FK] no_    | |[FK] no_      |")
output.append("| [FK] kode_brg| |    service| |    service | |    service | |    service   |")
output.append("|      qty     | |    kode_ | |    id_     | |    jenis_  | |    id_       |")
output.append("|      harga   | |    jasa  | |    keluhan | |    temuan  | |    keluhan   |")
output.append("|      total   | |    qty   | |    status  | |    deskripsi| |    status   |")
output.append("+--------------+ +----------+ +------------+ +------------+ +--------------+")

# Sales & Purchase Module
output.append("\n\n" + "=" * 100)
output.append("MODULE 3: SALES & PURCHASE TRANSACTIONS")
output.append("=" * 100)
output.append("")
output.append("+-------------------------------------+")
output.append("|      TBLSUPPLIER                    |")
output.append("+-------------------------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("|  TBLPEMBELIAN_HEADER (Purchase)     |         |  TBLPENJUALAN_HEADER (Sales)        |")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("| [PK] no_pembelian                   |         | [PK] no_penjualan                   |")
output.append("| [FK] kode_supplier                  |         | [FK] no_pelanggan                   |")
output.append("|      tanggal                        |         |      tanggal                        |")
output.append("|      total, ppn, grand_total        |         |      total, ppn, grand_total        |")
output.append("|      ... (32 columns)               |         |      ... (27 columns)               |")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("       | 1                                               | 1")
output.append("       |                                                 |")
output.append("       | *                                               | *")
output.append("       V                                                 V")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("|  TBLPEMBELIAN_DETAIL                |         |  TBLPENJUALAN_DETAIL                |")
output.append("+-------------------------------------+         +-------------------------------------+")
output.append("| [PK] id                             |         | [PK] id                             |")
output.append("| [FK] no_pembelian, kode_barang      |         | [FK] no_penjualan, kode_barang      |")
output.append("|      qty, harga, subtotal           |         |      qty, harga, subtotal           |")
output.append("+-------------------------------------+         +-------------------------------------+")

# Inventory Module
output.append("\n\n" + "=" * 100)
output.append("MODULE 4: INVENTORY MANAGEMENT")
output.append("=" * 100)
output.append("")
output.append("+---------------------------------------------------------------+")
output.append("|                    TBLITEM (Item/Product Master)              |")
output.append("+---------------------------------------------------------------+")
output.append("| [PK] kode_barang                                              |")
output.append("|      nama_barang, deskripsi                                   |")
output.append("|      kategori_barang, jenis_barang, satuan                    |")
output.append("|      harga_beli, harga_jual                                   |")
output.append("|      ... (49 columns total)                                   |")
output.append("+---------------------------------------------------------------+")
output.append("       |")
output.append("       +--------------+--------------+--------------+")
output.append("       | 1            | 1            | 1            | 1")
output.append("       |              |              |              |")
output.append("       | *            | *            | *            | *")
output.append("       V              V              V              V")
output.append("+--------------+ +----------+ +------------+ +------------+")
output.append("| TBLITEM_STOK | | TBLITEM_ | | TBLITEM_   | | TBSTOK     |")
output.append("|              | | JASA     | | SPART      | |            |")
output.append("+--------------+ +----------+ +------------+ +------------+")
output.append("| kode_barang  | |kode_jasa | | id         | | id         |")
output.append("| kode_cabang  | |nama_jasa | | kode_      | | kode_brg   |")
output.append("| stok_awal    | |harga     | | barang     | | kode_cab   |")
output.append("| stok_masuk   | |kategori  | | kode_      | | stok       |")
output.append("| stok_keluar  | |          | | supplier   | | tanggal    |")
output.append("| stok_akhir   | |          | |            | |            |")
output.append("+--------------+ +----------+ +------------+ +------------+")

# Procurement Module
output.append("\n\n" + "=" * 100)
output.append("MODULE 5: PROCUREMENT (PR -> PO -> DO)")
output.append("=" * 100)
output.append("")
output.append("+------------------------------+")
output.append("| TBLPURCHASE_REQUEST_HEADER   |  Step 1: Purchase Request")
output.append("+------------------------------+")
output.append("| [PK] no_pr                   |")
output.append("|      tanggal_pr              |")
output.append("|      status_approval         |")
output.append("+------------------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+------------------------------+")
output.append("| TBLPURCHASE_REQUEST_DETAIL   |")
output.append("+------------------------------+")
output.append("| [PK] id                      |")
output.append("| [FK] no_pr, kode_barang      |")
output.append("+------------------------------+")
output.append("       |")
output.append("       V")
output.append("+------------------------------+")
output.append("| TBLORDER_HEADER (PO)         |  Step 2: Purchase Order")
output.append("+------------------------------+")
output.append("| [PK] no_order                |")
output.append("| [FK] no_pr                   |")
output.append("|      kode_supplier           |")
output.append("+------------------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+------------------------------+")
output.append("| TBLORDER_DETAIL              |")
output.append("+------------------------------+")
output.append("| [PK] id                      |")
output.append("| [FK] no_order, kode_barang   |")
output.append("+------------------------------+")
output.append("       |")
output.append("       V")
output.append("+------------------------------+")
output.append("| TBLDELIVERY_ORDER_HEADER     |  Step 3: Delivery Order")
output.append("+------------------------------+")
output.append("| [PK] no_do                   |")
output.append("| [FK] no_order                |")
output.append("|      tanggal_kirim           |")
output.append("+------------------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+------------------------------+")
output.append("| TBLDELIVERY_ORDER_DETAIL     |")
output.append("+------------------------------+")
output.append("| [PK] id                      |")
output.append("| [FK] no_do, kode_barang      |")
output.append("+------------------------------+")

# User & RBAC Module
output.append("\n\n" + "=" * 100)
output.append("MODULE 6: USER MANAGEMENT & RBAC")
output.append("=" * 100)
output.append("")
output.append("+-------------------------+         +-------------------------+")
output.append("| TB_USER_ACCOUNT         |         | TB_USER_ROLES           |")
output.append("+-------------------------+         +-------------------------+")
output.append("| [PK] id                 |         | [PK] id                 |")
output.append("|      username           | * >-----< *  role_name             |")
output.append("|      password           |         |      role_description   |")
output.append("|      role_id            |         |      permissions        |")
output.append("+-------------------------+         +-------------------------+")
output.append("       | 1                                   | 1")
output.append("       |                                     |")
output.append("       | *                                   | *")
output.append("       V                                     V")
output.append("+-------------------------+         +-------------------------+")
output.append("| TB_USER_ACTIVITY_LOG    |         | TB_PERMISSIONS          |")
output.append("+-------------------------+         +-------------------------+")
output.append("| [PK] id                 |         | [PK] id                 |")
output.append("| [FK] user_id            |         |      permission_name    |")
output.append("|      action             |         |      permission_type    |")
output.append("|      timestamp          |         |      module             |")
output.append("+-------------------------+         +-------------------------+")

# Master Data Relationships
output.append("\n\n" + "=" * 100)
output.append("MODULE 7: MASTER DATA & LOOKUP TABLES")
output.append("=" * 100)
output.append("")
output.append("Vehicle Type Hierarchy:")
output.append("")
output.append("+---------------------+")
output.append("| TBPABRIK_MOTOR      |  (Brand: Honda, Yamaha, etc)")
output.append("+---------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+---------------------+")
output.append("| TBJENIS_MOTOR       |  (Type: Sport, Matic, etc)")
output.append("+---------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+---------------------+")
output.append("| TBKATEGORI_MOTOR    |  (Category)")
output.append("+---------------------+")
output.append("       | 1")
output.append("       |")
output.append("       | *")
output.append("       V")
output.append("+---------------------+")
output.append("| TBTIPE_MOTOR        |  (Model: Beat, Vario, etc)")
output.append("+---------------------+")

# Header-Detail Pairs Summary
output.append("\n\n" + "=" * 100)
output.append("HEADER-DETAIL RELATIONSHIP PAIRS")
output.append("=" * 100)
output.append("")

for pair in relationships['header_detail_pairs']:
    output.append(f"{pair['header']:40s} 1 ----< * {pair['detail']}")

# Write to file
with open('DATABASE_ERD.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(output))

print(f"Generated DATABASE_ERD.txt ({len(output)} lines)")
